### ISSUE TITLE
Flatpak version does not include "game.so" files

### ISSUE THREAD

**Issue by HellsBells24** [flathub/org.yamagi.YamagiQ2#3] opened 2021-02-01 13:56 UTC
Yesterday I was using the YQ2 flatpak to play Rogue's Quake II Ground Zero on Pop!_OS. As I moved through the first level, I discovered that the Double Damage powerup was missing from the level's first secret area, and the elevator that leads into the upper floor of the level was non functional. I was informed that this was due to the lack of "game.so" files in the rogue directory. I was able to pull these from a Kubuntu installation where I have the game installed in the more traditional manner, and play the game as normal.
While researching this it was suggested that I let the Flatpak maintainers know that the game.so files required to play the expansions are not included in the flatpak installation. Please let me know if any more info is needed.

**Comment by Eonfge** [comment] 2021-02-01 15:33
Hey, could you check something for me, can you run the following:
```tree /var/lib/flatpak/app/org.yamagi.YamagiQ2/current/active/files```

I'm surprised because I do actually package the game.so for all expansions. I'll research it and I'll also prepare the next minor patch

**Comment by HellsBells24** [comment] 2021-02-01 15:35
I'm not home at the moment, but i'll do so when I'm near that PC again.
For reference, I obtained this flatpak from the Pop Shop.

**Comment by Eonfge** [comment] 2021-02-01 15:41
The Pop store is [Flathub](https://flathub.org/home), but integrated. Also, I just reproduced the issue, but it's also a more difficult one to fix on my side. The problem is that I split the binaries from the assets, so the assets are in your user-folder, but the binaries are in the system-folder. This works for the base game, but not for the expansions. I'll ask upstream

**Comment by Eonfge** [comment] 2021-02-01 15:50
Upsteam question:
https://github.com/yquake2/rogue/issues/77

As a work around, you can copy the game.so files from `/var/lib/flatpak/app/org.yamagi.YamagiQ2/current/active/files/bin` to your data directory. Not great, but if all else fails I'll automate it for you in the future.

**Comment by Eonfge** [comment] 2021-02-02 17:43
Should be fixed now... I had misspelled rogue.

**Closed by Eonfge** 2021-02-02 17:43 UTC
